### ISSUE TITLE
Adding undo redo functionality for workbook

### ISSUE THREAD

**Issue by JithinKS97** [dynamic-learning/dynamic-learning#28]
Add undo-redo functionality for workbook
Workbook state is defined by the object 
```
{
  slides,
  curSlide
}
```
Whenever a change happens for this object, it has to be pushed to undo stack.
Refer to this article in redux docs
https://redux.js.org/recipes/implementing-undo-history

There can be more items in the state. So basically out approach should be to store the undo and redo histories of an arbitrary state (Object).

Appropriate test cases are also needed.

**Comment by Aswin40** [comment]
Can we create a general reducer so that any object can be kept track of ?

**Comment by JithinKS97** [comment]
Yeah, that will make the code more structured.

**Comment by Aswin40** [comment]
Okay I have added the undo and redo operations only for the workbook.

**Comment by JithinKS97** [comment]
Resolved with #33
